controller_manager:
  ros__parameters:
    update_rate: 15
    use_sim_time: true

    acker_cont:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

acker_cont:
  ros__parameters:

    rear_wheels_names: [rear_right_wheel_joint, rear_left_wheel_joint]
    front_wheels_names: [front_right_steering_joint, front_left_steering_joint]
    base_frame_id: footprint_link

    wheelbase: 0.6
    front_wheel_track: 0.42
    rear_wheel_track: 0.42
    front_wheels_radius: 0.1
    rear_wheels_radius: 0.1 

# joint_broad:
#   ros__parameters: